/*
 * generated by Xtext 2.23.0
 */
package org.xtext.example.idmproject.tests

import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith
import org.xtext.example.idmproject.jsonParser.JsonModel
import org.junit.jupiter.api.Order
import org.junit.jupiter.api.TestMethodOrder
import org.junit.jupiter.api.MethodOrderer.OrderAnnotation;
import org.junit.jupiter.api.Disabled

@ExtendWith(InjectionExtension)
@InjectWith(JsonParserInjectorProvider)
@TestMethodOrder(OrderAnnotation) 
class JsonParserParsingTest {
	@Inject
	ParseHelper<JsonModel> parseHelper
	
	@Test
	@Order(1)
	def void loadBaseFile() {
		val result = parseHelper.parse('''
			.load("file.json")
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
		
		val PythonCompiler cmpPython = new PythonCompiler(result)
		cmpPython.compileAndRun
		
		val JavaCompiler cmplJava = new JavaCompiler(result)
		cmplJava.compileAndRun	
	}
	
	@Test
	@Order(2)
	def void selectData() {
		val result = parseHelper.parse('''
			.load("file.json")
			expr id1 =.select("key1")
			expr id2 =.select("key1")
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
		
		val PythonCompiler cmpPython = new PythonCompiler(result)
		cmpPython.compileAndRun
		
		val JavaCompiler cmplJava = new JavaCompiler(result)
		cmplJava.compileAndRun
	}

	@Test
	@Order(3)
	def void storeData() {
		val result = parseHelper.parse('''
			.load("file.json")
			.store("newFile1.json")
			.store("newFile2.json")
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
		
		val PythonCompiler cmpPython = new PythonCompiler(result)
		cmpPython.compileAndRun
		
		val JavaCompiler cmplJava = new JavaCompiler(result)
		cmplJava.compileAndRun
	}
	
	@Test
	@Order(4)
	def void insertData() {
		val result = parseHelper.parse('''
			.load("file.json")
			.insert("newKey1","\"newValue1\"")
			.insert("newKey2","\"newValue2\"")
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
		
		val PythonCompiler cmpPython = new PythonCompiler(result)
		cmpPython.compileAndRun
		
		val JavaCompiler cmplJava = new JavaCompiler(result)
		cmplJava.compileAndRun
	}
	
	@Test
	@Order(5)
	def void printData() {
		val result = parseHelper.parse('''
			.load("file.json")
			.print("key1")
			.print("key2")
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
		
		val PythonCompiler cmpPython = new PythonCompiler(result)
		cmpPython.compileAndRun
		
		val JavaCompiler cmplJava = new JavaCompiler(result)
		cmplJava.compileAndRun
	}
	
	@Test
	@Order(6)
	def void updateData() {
		val result = parseHelper.parse('''
			.load("file.json")
			.update("key1","\"updatedValue1\"")
			.update("key2","\"updatedValue2\"")
			.save()
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
		
		val PythonCompiler cmpPython = new PythonCompiler(result)
		cmpPython.compileAndRun
		
		val JavaCompiler cmplJava = new JavaCompiler(result)
		cmplJava.compileAndRun	
	}
	
	@Test
	@Order(7)
	def void computeData() {
		val result = parseHelper.parse('''
			.load("file.json")
			.sum("key3" + "key4")
			.product("key3" * "key4")
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
		
		val PythonCompiler cmpPython = new PythonCompiler(result)
		cmpPython.compileAndRun
		
		val JavaCompiler cmplJava = new JavaCompiler(result)
		cmplJava.compileAndRun	
	}
	
	@Test
	@Order(8)
	def void saveData() {
		val result = parseHelper.parse('''
			.load("file.json")
			.save()
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
		
		val PythonCompiler cmpPython = new PythonCompiler(result)
		cmpPython.compileAndRun
		
		val JavaCompiler cmplJava = new JavaCompiler(result)
		cmplJava.compileAndRun	
	}
}
