/*
 * generated by Xtext 2.23.0
 */
package org.xtext.example.idmproject.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class JsonParserAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/xtext/example/idmproject/parser/antlr/internal/InternalJsonParser.tokens");
	}
}
