/*
 * generated by Xtext 2.23.0
 */
package org.xtext.example.idmproject.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.idmproject.parser.antlr.internal.InternalJsonParserParser;
import org.xtext.example.idmproject.services.JsonParserGrammarAccess;

public class JsonParserParser extends AbstractAntlrParser {

	@Inject
	private JsonParserGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalJsonParserParser createParser(XtextTokenStream stream) {
		return new InternalJsonParserParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "JsonModel";
	}

	public JsonParserGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(JsonParserGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
