/**
 * generated by Xtext 2.23.0
 */
package org.xtext.example.idmproject.jsonParser;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Compute</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.idmproject.jsonParser.Compute#getKey1 <em>Key1</em>}</li>
 *   <li>{@link org.xtext.example.idmproject.jsonParser.Compute#getKey2 <em>Key2</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.idmproject.jsonParser.JsonParserPackage#getCompute()
 * @model
 * @generated
 */
public interface Compute extends EObject
{
  /**
   * Returns the value of the '<em><b>Key1</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Key1</em>' attribute.
   * @see #setKey1(String)
   * @see org.xtext.example.idmproject.jsonParser.JsonParserPackage#getCompute_Key1()
   * @model
   * @generated
   */
  String getKey1();

  /**
   * Sets the value of the '{@link org.xtext.example.idmproject.jsonParser.Compute#getKey1 <em>Key1</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Key1</em>' attribute.
   * @see #getKey1()
   * @generated
   */
  void setKey1(String value);

  /**
   * Returns the value of the '<em><b>Key2</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Key2</em>' attribute.
   * @see #setKey2(String)
   * @see org.xtext.example.idmproject.jsonParser.JsonParserPackage#getCompute_Key2()
   * @model
   * @generated
   */
  String getKey2();

  /**
   * Sets the value of the '{@link org.xtext.example.idmproject.jsonParser.Compute#getKey2 <em>Key2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Key2</em>' attribute.
   * @see #getKey2()
   * @generated
   */
  void setKey2(String value);

} // Compute
