/**
 * generated by Xtext 2.23.0
 */
package org.xtext.example.idmproject.jsonParser;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.idmproject.jsonParser.JsonParserFactory
 * @model kind="package"
 * @generated
 */
public interface JsonParserPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "jsonParser";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/idmproject/JsonParser";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "jsonParser";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  JsonParserPackage eINSTANCE = org.xtext.example.idmproject.jsonParser.impl.JsonParserPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.idmproject.jsonParser.impl.JsonModelImpl <em>Json Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.idmproject.jsonParser.impl.JsonModelImpl
   * @see org.xtext.example.idmproject.jsonParser.impl.JsonParserPackageImpl#getJsonModel()
   * @generated
   */
  int JSON_MODEL = 0;

  /**
   * The feature id for the '<em><b>Base Load</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JSON_MODEL__BASE_LOAD = 0;

  /**
   * The feature id for the '<em><b>Instructions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JSON_MODEL__INSTRUCTIONS = 1;

  /**
   * The number of structural features of the '<em>Json Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JSON_MODEL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.idmproject.jsonParser.impl.InstructionImpl <em>Instruction</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.idmproject.jsonParser.impl.InstructionImpl
   * @see org.xtext.example.idmproject.jsonParser.impl.JsonParserPackageImpl#getInstruction()
   * @generated
   */
  int INSTRUCTION = 1;

  /**
   * The feature id for the '<em><b>Select</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSTRUCTION__SELECT = 0;

  /**
   * The feature id for the '<em><b>Store</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSTRUCTION__STORE = 1;

  /**
   * The feature id for the '<em><b>Save</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSTRUCTION__SAVE = 2;

  /**
   * The feature id for the '<em><b>Print</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSTRUCTION__PRINT = 3;

  /**
   * The feature id for the '<em><b>Insert</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSTRUCTION__INSERT = 4;

  /**
   * The feature id for the '<em><b>Update</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSTRUCTION__UPDATE = 5;

  /**
   * The feature id for the '<em><b>Compute</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSTRUCTION__COMPUTE = 6;

  /**
   * The feature id for the '<em><b>Get</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSTRUCTION__GET = 7;

  /**
   * The number of structural features of the '<em>Instruction</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSTRUCTION_FEATURE_COUNT = 8;

  /**
   * The meta object id for the '{@link org.xtext.example.idmproject.jsonParser.impl.LoadImpl <em>Load</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.idmproject.jsonParser.impl.LoadImpl
   * @see org.xtext.example.idmproject.jsonParser.impl.JsonParserPackageImpl#getLoad()
   * @generated
   */
  int LOAD = 2;

  /**
   * The feature id for the '<em><b>File</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOAD__FILE = 0;

  /**
   * The number of structural features of the '<em>Load</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOAD_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.idmproject.jsonParser.impl.SelectImpl <em>Select</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.idmproject.jsonParser.impl.SelectImpl
   * @see org.xtext.example.idmproject.jsonParser.impl.JsonParserPackageImpl#getSelect()
   * @generated
   */
  int SELECT = 3;

  /**
   * The feature id for the '<em><b>ID</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECT__ID = 0;

  /**
   * The feature id for the '<em><b>Key</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECT__KEY = 1;

  /**
   * The number of structural features of the '<em>Select</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.idmproject.jsonParser.impl.StoreImpl <em>Store</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.idmproject.jsonParser.impl.StoreImpl
   * @see org.xtext.example.idmproject.jsonParser.impl.JsonParserPackageImpl#getStore()
   * @generated
   */
  int STORE = 4;

  /**
   * The feature id for the '<em><b>File</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STORE__FILE = 0;

  /**
   * The number of structural features of the '<em>Store</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STORE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.idmproject.jsonParser.impl.PrintImpl <em>Print</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.idmproject.jsonParser.impl.PrintImpl
   * @see org.xtext.example.idmproject.jsonParser.impl.JsonParserPackageImpl#getPrint()
   * @generated
   */
  int PRINT = 5;

  /**
   * The feature id for the '<em><b>Key</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRINT__KEY = 0;

  /**
   * The number of structural features of the '<em>Print</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRINT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.idmproject.jsonParser.impl.GetValueImpl <em>Get Value</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.idmproject.jsonParser.impl.GetValueImpl
   * @see org.xtext.example.idmproject.jsonParser.impl.JsonParserPackageImpl#getGetValue()
   * @generated
   */
  int GET_VALUE = 6;

  /**
   * The feature id for the '<em><b>Key</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GET_VALUE__KEY = 0;

  /**
   * The number of structural features of the '<em>Get Value</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GET_VALUE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.idmproject.jsonParser.impl.InsertImpl <em>Insert</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.idmproject.jsonParser.impl.InsertImpl
   * @see org.xtext.example.idmproject.jsonParser.impl.JsonParserPackageImpl#getInsert()
   * @generated
   */
  int INSERT = 7;

  /**
   * The feature id for the '<em><b>Key</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSERT__KEY = 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSERT__VALUE = 1;

  /**
   * The number of structural features of the '<em>Insert</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSERT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.idmproject.jsonParser.impl.UpdateImpl <em>Update</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.idmproject.jsonParser.impl.UpdateImpl
   * @see org.xtext.example.idmproject.jsonParser.impl.JsonParserPackageImpl#getUpdate()
   * @generated
   */
  int UPDATE = 8;

  /**
   * The feature id for the '<em><b>Key</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UPDATE__KEY = 0;

  /**
   * The feature id for the '<em><b>New Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UPDATE__NEW_VALUE = 1;

  /**
   * The number of structural features of the '<em>Update</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UPDATE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.idmproject.jsonParser.impl.ComputeImpl <em>Compute</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.idmproject.jsonParser.impl.ComputeImpl
   * @see org.xtext.example.idmproject.jsonParser.impl.JsonParserPackageImpl#getCompute()
   * @generated
   */
  int COMPUTE = 9;

  /**
   * The feature id for the '<em><b>Key1</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPUTE__KEY1 = 0;

  /**
   * The feature id for the '<em><b>Key2</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPUTE__KEY2 = 1;

  /**
   * The number of structural features of the '<em>Compute</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPUTE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.idmproject.jsonParser.impl.SumImpl <em>Sum</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.idmproject.jsonParser.impl.SumImpl
   * @see org.xtext.example.idmproject.jsonParser.impl.JsonParserPackageImpl#getSum()
   * @generated
   */
  int SUM = 10;

  /**
   * The feature id for the '<em><b>Key1</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUM__KEY1 = COMPUTE__KEY1;

  /**
   * The feature id for the '<em><b>Key2</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUM__KEY2 = COMPUTE__KEY2;

  /**
   * The number of structural features of the '<em>Sum</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUM_FEATURE_COUNT = COMPUTE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.idmproject.jsonParser.impl.ProductImpl <em>Product</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.idmproject.jsonParser.impl.ProductImpl
   * @see org.xtext.example.idmproject.jsonParser.impl.JsonParserPackageImpl#getProduct()
   * @generated
   */
  int PRODUCT = 11;

  /**
   * The feature id for the '<em><b>Key1</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRODUCT__KEY1 = COMPUTE__KEY1;

  /**
   * The feature id for the '<em><b>Key2</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRODUCT__KEY2 = COMPUTE__KEY2;

  /**
   * The number of structural features of the '<em>Product</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRODUCT_FEATURE_COUNT = COMPUTE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.idmproject.jsonParser.impl.ExpressionImpl <em>Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.idmproject.jsonParser.impl.ExpressionImpl
   * @see org.xtext.example.idmproject.jsonParser.impl.JsonParserPackageImpl#getExpression()
   * @generated
   */
  int EXPRESSION = 12;

  /**
   * The feature id for the '<em><b>Key</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__KEY = 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__VALUE = 1;

  /**
   * The number of structural features of the '<em>Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.idmproject.jsonParser.impl.ValueImpl <em>Value</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.idmproject.jsonParser.impl.ValueImpl
   * @see org.xtext.example.idmproject.jsonParser.impl.JsonParserPackageImpl#getValue()
   * @generated
   */
  int VALUE = 13;

  /**
   * The feature id for the '<em><b>String Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VALUE__STRING_VALUE = 0;

  /**
   * The feature id for the '<em><b>Integer Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VALUE__INTEGER_VALUE = 1;

  /**
   * The feature id for the '<em><b>Array</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VALUE__ARRAY = 2;

  /**
   * The number of structural features of the '<em>Value</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VALUE_FEATURE_COUNT = 3;


  /**
   * Returns the meta object for class '{@link org.xtext.example.idmproject.jsonParser.JsonModel <em>Json Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Json Model</em>'.
   * @see org.xtext.example.idmproject.jsonParser.JsonModel
   * @generated
   */
  EClass getJsonModel();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.idmproject.jsonParser.JsonModel#getBaseLoad <em>Base Load</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Base Load</em>'.
   * @see org.xtext.example.idmproject.jsonParser.JsonModel#getBaseLoad()
   * @see #getJsonModel()
   * @generated
   */
  EReference getJsonModel_BaseLoad();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.idmproject.jsonParser.JsonModel#getInstructions <em>Instructions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Instructions</em>'.
   * @see org.xtext.example.idmproject.jsonParser.JsonModel#getInstructions()
   * @see #getJsonModel()
   * @generated
   */
  EReference getJsonModel_Instructions();

  /**
   * Returns the meta object for class '{@link org.xtext.example.idmproject.jsonParser.Instruction <em>Instruction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Instruction</em>'.
   * @see org.xtext.example.idmproject.jsonParser.Instruction
   * @generated
   */
  EClass getInstruction();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.idmproject.jsonParser.Instruction#getSelect <em>Select</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Select</em>'.
   * @see org.xtext.example.idmproject.jsonParser.Instruction#getSelect()
   * @see #getInstruction()
   * @generated
   */
  EReference getInstruction_Select();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.idmproject.jsonParser.Instruction#getStore <em>Store</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Store</em>'.
   * @see org.xtext.example.idmproject.jsonParser.Instruction#getStore()
   * @see #getInstruction()
   * @generated
   */
  EReference getInstruction_Store();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.idmproject.jsonParser.Instruction#getSave <em>Save</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Save</em>'.
   * @see org.xtext.example.idmproject.jsonParser.Instruction#getSave()
   * @see #getInstruction()
   * @generated
   */
  EAttribute getInstruction_Save();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.idmproject.jsonParser.Instruction#getPrint <em>Print</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Print</em>'.
   * @see org.xtext.example.idmproject.jsonParser.Instruction#getPrint()
   * @see #getInstruction()
   * @generated
   */
  EReference getInstruction_Print();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.idmproject.jsonParser.Instruction#getInsert <em>Insert</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Insert</em>'.
   * @see org.xtext.example.idmproject.jsonParser.Instruction#getInsert()
   * @see #getInstruction()
   * @generated
   */
  EReference getInstruction_Insert();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.idmproject.jsonParser.Instruction#getUpdate <em>Update</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Update</em>'.
   * @see org.xtext.example.idmproject.jsonParser.Instruction#getUpdate()
   * @see #getInstruction()
   * @generated
   */
  EReference getInstruction_Update();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.idmproject.jsonParser.Instruction#getCompute <em>Compute</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Compute</em>'.
   * @see org.xtext.example.idmproject.jsonParser.Instruction#getCompute()
   * @see #getInstruction()
   * @generated
   */
  EReference getInstruction_Compute();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.idmproject.jsonParser.Instruction#getGet <em>Get</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Get</em>'.
   * @see org.xtext.example.idmproject.jsonParser.Instruction#getGet()
   * @see #getInstruction()
   * @generated
   */
  EReference getInstruction_Get();

  /**
   * Returns the meta object for class '{@link org.xtext.example.idmproject.jsonParser.Load <em>Load</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Load</em>'.
   * @see org.xtext.example.idmproject.jsonParser.Load
   * @generated
   */
  EClass getLoad();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.idmproject.jsonParser.Load#getFile <em>File</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>File</em>'.
   * @see org.xtext.example.idmproject.jsonParser.Load#getFile()
   * @see #getLoad()
   * @generated
   */
  EAttribute getLoad_File();

  /**
   * Returns the meta object for class '{@link org.xtext.example.idmproject.jsonParser.Select <em>Select</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Select</em>'.
   * @see org.xtext.example.idmproject.jsonParser.Select
   * @generated
   */
  EClass getSelect();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.idmproject.jsonParser.Select#getID <em>ID</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>ID</em>'.
   * @see org.xtext.example.idmproject.jsonParser.Select#getID()
   * @see #getSelect()
   * @generated
   */
  EAttribute getSelect_ID();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.idmproject.jsonParser.Select#getKey <em>Key</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Key</em>'.
   * @see org.xtext.example.idmproject.jsonParser.Select#getKey()
   * @see #getSelect()
   * @generated
   */
  EAttribute getSelect_Key();

  /**
   * Returns the meta object for class '{@link org.xtext.example.idmproject.jsonParser.Store <em>Store</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Store</em>'.
   * @see org.xtext.example.idmproject.jsonParser.Store
   * @generated
   */
  EClass getStore();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.idmproject.jsonParser.Store#getFile <em>File</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>File</em>'.
   * @see org.xtext.example.idmproject.jsonParser.Store#getFile()
   * @see #getStore()
   * @generated
   */
  EAttribute getStore_File();

  /**
   * Returns the meta object for class '{@link org.xtext.example.idmproject.jsonParser.Print <em>Print</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Print</em>'.
   * @see org.xtext.example.idmproject.jsonParser.Print
   * @generated
   */
  EClass getPrint();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.idmproject.jsonParser.Print#getKey <em>Key</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Key</em>'.
   * @see org.xtext.example.idmproject.jsonParser.Print#getKey()
   * @see #getPrint()
   * @generated
   */
  EAttribute getPrint_Key();

  /**
   * Returns the meta object for class '{@link org.xtext.example.idmproject.jsonParser.GetValue <em>Get Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Get Value</em>'.
   * @see org.xtext.example.idmproject.jsonParser.GetValue
   * @generated
   */
  EClass getGetValue();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.idmproject.jsonParser.GetValue#getKey <em>Key</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Key</em>'.
   * @see org.xtext.example.idmproject.jsonParser.GetValue#getKey()
   * @see #getGetValue()
   * @generated
   */
  EAttribute getGetValue_Key();

  /**
   * Returns the meta object for class '{@link org.xtext.example.idmproject.jsonParser.Insert <em>Insert</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Insert</em>'.
   * @see org.xtext.example.idmproject.jsonParser.Insert
   * @generated
   */
  EClass getInsert();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.idmproject.jsonParser.Insert#getKey <em>Key</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Key</em>'.
   * @see org.xtext.example.idmproject.jsonParser.Insert#getKey()
   * @see #getInsert()
   * @generated
   */
  EAttribute getInsert_Key();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.idmproject.jsonParser.Insert#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see org.xtext.example.idmproject.jsonParser.Insert#getValue()
   * @see #getInsert()
   * @generated
   */
  EReference getInsert_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.example.idmproject.jsonParser.Update <em>Update</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Update</em>'.
   * @see org.xtext.example.idmproject.jsonParser.Update
   * @generated
   */
  EClass getUpdate();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.idmproject.jsonParser.Update#getKey <em>Key</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Key</em>'.
   * @see org.xtext.example.idmproject.jsonParser.Update#getKey()
   * @see #getUpdate()
   * @generated
   */
  EAttribute getUpdate_Key();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.idmproject.jsonParser.Update#getNewValue <em>New Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>New Value</em>'.
   * @see org.xtext.example.idmproject.jsonParser.Update#getNewValue()
   * @see #getUpdate()
   * @generated
   */
  EReference getUpdate_NewValue();

  /**
   * Returns the meta object for class '{@link org.xtext.example.idmproject.jsonParser.Compute <em>Compute</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Compute</em>'.
   * @see org.xtext.example.idmproject.jsonParser.Compute
   * @generated
   */
  EClass getCompute();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.idmproject.jsonParser.Compute#getKey1 <em>Key1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Key1</em>'.
   * @see org.xtext.example.idmproject.jsonParser.Compute#getKey1()
   * @see #getCompute()
   * @generated
   */
  EAttribute getCompute_Key1();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.idmproject.jsonParser.Compute#getKey2 <em>Key2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Key2</em>'.
   * @see org.xtext.example.idmproject.jsonParser.Compute#getKey2()
   * @see #getCompute()
   * @generated
   */
  EAttribute getCompute_Key2();

  /**
   * Returns the meta object for class '{@link org.xtext.example.idmproject.jsonParser.Sum <em>Sum</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Sum</em>'.
   * @see org.xtext.example.idmproject.jsonParser.Sum
   * @generated
   */
  EClass getSum();

  /**
   * Returns the meta object for class '{@link org.xtext.example.idmproject.jsonParser.Product <em>Product</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Product</em>'.
   * @see org.xtext.example.idmproject.jsonParser.Product
   * @generated
   */
  EClass getProduct();

  /**
   * Returns the meta object for class '{@link org.xtext.example.idmproject.jsonParser.Expression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expression</em>'.
   * @see org.xtext.example.idmproject.jsonParser.Expression
   * @generated
   */
  EClass getExpression();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.idmproject.jsonParser.Expression#getKey <em>Key</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Key</em>'.
   * @see org.xtext.example.idmproject.jsonParser.Expression#getKey()
   * @see #getExpression()
   * @generated
   */
  EAttribute getExpression_Key();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.idmproject.jsonParser.Expression#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see org.xtext.example.idmproject.jsonParser.Expression#getValue()
   * @see #getExpression()
   * @generated
   */
  EReference getExpression_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.example.idmproject.jsonParser.Value <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Value</em>'.
   * @see org.xtext.example.idmproject.jsonParser.Value
   * @generated
   */
  EClass getValue();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.idmproject.jsonParser.Value#getStringValue <em>String Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>String Value</em>'.
   * @see org.xtext.example.idmproject.jsonParser.Value#getStringValue()
   * @see #getValue()
   * @generated
   */
  EAttribute getValue_StringValue();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.idmproject.jsonParser.Value#getIntegerValue <em>Integer Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Integer Value</em>'.
   * @see org.xtext.example.idmproject.jsonParser.Value#getIntegerValue()
   * @see #getValue()
   * @generated
   */
  EAttribute getValue_IntegerValue();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.idmproject.jsonParser.Value#getArray <em>Array</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Array</em>'.
   * @see org.xtext.example.idmproject.jsonParser.Value#getArray()
   * @see #getValue()
   * @generated
   */
  EAttribute getValue_Array();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  JsonParserFactory getJsonParserFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.idmproject.jsonParser.impl.JsonModelImpl <em>Json Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.idmproject.jsonParser.impl.JsonModelImpl
     * @see org.xtext.example.idmproject.jsonParser.impl.JsonParserPackageImpl#getJsonModel()
     * @generated
     */
    EClass JSON_MODEL = eINSTANCE.getJsonModel();

    /**
     * The meta object literal for the '<em><b>Base Load</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference JSON_MODEL__BASE_LOAD = eINSTANCE.getJsonModel_BaseLoad();

    /**
     * The meta object literal for the '<em><b>Instructions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference JSON_MODEL__INSTRUCTIONS = eINSTANCE.getJsonModel_Instructions();

    /**
     * The meta object literal for the '{@link org.xtext.example.idmproject.jsonParser.impl.InstructionImpl <em>Instruction</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.idmproject.jsonParser.impl.InstructionImpl
     * @see org.xtext.example.idmproject.jsonParser.impl.JsonParserPackageImpl#getInstruction()
     * @generated
     */
    EClass INSTRUCTION = eINSTANCE.getInstruction();

    /**
     * The meta object literal for the '<em><b>Select</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INSTRUCTION__SELECT = eINSTANCE.getInstruction_Select();

    /**
     * The meta object literal for the '<em><b>Store</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INSTRUCTION__STORE = eINSTANCE.getInstruction_Store();

    /**
     * The meta object literal for the '<em><b>Save</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INSTRUCTION__SAVE = eINSTANCE.getInstruction_Save();

    /**
     * The meta object literal for the '<em><b>Print</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INSTRUCTION__PRINT = eINSTANCE.getInstruction_Print();

    /**
     * The meta object literal for the '<em><b>Insert</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INSTRUCTION__INSERT = eINSTANCE.getInstruction_Insert();

    /**
     * The meta object literal for the '<em><b>Update</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INSTRUCTION__UPDATE = eINSTANCE.getInstruction_Update();

    /**
     * The meta object literal for the '<em><b>Compute</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INSTRUCTION__COMPUTE = eINSTANCE.getInstruction_Compute();

    /**
     * The meta object literal for the '<em><b>Get</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INSTRUCTION__GET = eINSTANCE.getInstruction_Get();

    /**
     * The meta object literal for the '{@link org.xtext.example.idmproject.jsonParser.impl.LoadImpl <em>Load</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.idmproject.jsonParser.impl.LoadImpl
     * @see org.xtext.example.idmproject.jsonParser.impl.JsonParserPackageImpl#getLoad()
     * @generated
     */
    EClass LOAD = eINSTANCE.getLoad();

    /**
     * The meta object literal for the '<em><b>File</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LOAD__FILE = eINSTANCE.getLoad_File();

    /**
     * The meta object literal for the '{@link org.xtext.example.idmproject.jsonParser.impl.SelectImpl <em>Select</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.idmproject.jsonParser.impl.SelectImpl
     * @see org.xtext.example.idmproject.jsonParser.impl.JsonParserPackageImpl#getSelect()
     * @generated
     */
    EClass SELECT = eINSTANCE.getSelect();

    /**
     * The meta object literal for the '<em><b>ID</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SELECT__ID = eINSTANCE.getSelect_ID();

    /**
     * The meta object literal for the '<em><b>Key</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SELECT__KEY = eINSTANCE.getSelect_Key();

    /**
     * The meta object literal for the '{@link org.xtext.example.idmproject.jsonParser.impl.StoreImpl <em>Store</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.idmproject.jsonParser.impl.StoreImpl
     * @see org.xtext.example.idmproject.jsonParser.impl.JsonParserPackageImpl#getStore()
     * @generated
     */
    EClass STORE = eINSTANCE.getStore();

    /**
     * The meta object literal for the '<em><b>File</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STORE__FILE = eINSTANCE.getStore_File();

    /**
     * The meta object literal for the '{@link org.xtext.example.idmproject.jsonParser.impl.PrintImpl <em>Print</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.idmproject.jsonParser.impl.PrintImpl
     * @see org.xtext.example.idmproject.jsonParser.impl.JsonParserPackageImpl#getPrint()
     * @generated
     */
    EClass PRINT = eINSTANCE.getPrint();

    /**
     * The meta object literal for the '<em><b>Key</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PRINT__KEY = eINSTANCE.getPrint_Key();

    /**
     * The meta object literal for the '{@link org.xtext.example.idmproject.jsonParser.impl.GetValueImpl <em>Get Value</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.idmproject.jsonParser.impl.GetValueImpl
     * @see org.xtext.example.idmproject.jsonParser.impl.JsonParserPackageImpl#getGetValue()
     * @generated
     */
    EClass GET_VALUE = eINSTANCE.getGetValue();

    /**
     * The meta object literal for the '<em><b>Key</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GET_VALUE__KEY = eINSTANCE.getGetValue_Key();

    /**
     * The meta object literal for the '{@link org.xtext.example.idmproject.jsonParser.impl.InsertImpl <em>Insert</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.idmproject.jsonParser.impl.InsertImpl
     * @see org.xtext.example.idmproject.jsonParser.impl.JsonParserPackageImpl#getInsert()
     * @generated
     */
    EClass INSERT = eINSTANCE.getInsert();

    /**
     * The meta object literal for the '<em><b>Key</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INSERT__KEY = eINSTANCE.getInsert_Key();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INSERT__VALUE = eINSTANCE.getInsert_Value();

    /**
     * The meta object literal for the '{@link org.xtext.example.idmproject.jsonParser.impl.UpdateImpl <em>Update</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.idmproject.jsonParser.impl.UpdateImpl
     * @see org.xtext.example.idmproject.jsonParser.impl.JsonParserPackageImpl#getUpdate()
     * @generated
     */
    EClass UPDATE = eINSTANCE.getUpdate();

    /**
     * The meta object literal for the '<em><b>Key</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute UPDATE__KEY = eINSTANCE.getUpdate_Key();

    /**
     * The meta object literal for the '<em><b>New Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference UPDATE__NEW_VALUE = eINSTANCE.getUpdate_NewValue();

    /**
     * The meta object literal for the '{@link org.xtext.example.idmproject.jsonParser.impl.ComputeImpl <em>Compute</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.idmproject.jsonParser.impl.ComputeImpl
     * @see org.xtext.example.idmproject.jsonParser.impl.JsonParserPackageImpl#getCompute()
     * @generated
     */
    EClass COMPUTE = eINSTANCE.getCompute();

    /**
     * The meta object literal for the '<em><b>Key1</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMPUTE__KEY1 = eINSTANCE.getCompute_Key1();

    /**
     * The meta object literal for the '<em><b>Key2</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMPUTE__KEY2 = eINSTANCE.getCompute_Key2();

    /**
     * The meta object literal for the '{@link org.xtext.example.idmproject.jsonParser.impl.SumImpl <em>Sum</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.idmproject.jsonParser.impl.SumImpl
     * @see org.xtext.example.idmproject.jsonParser.impl.JsonParserPackageImpl#getSum()
     * @generated
     */
    EClass SUM = eINSTANCE.getSum();

    /**
     * The meta object literal for the '{@link org.xtext.example.idmproject.jsonParser.impl.ProductImpl <em>Product</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.idmproject.jsonParser.impl.ProductImpl
     * @see org.xtext.example.idmproject.jsonParser.impl.JsonParserPackageImpl#getProduct()
     * @generated
     */
    EClass PRODUCT = eINSTANCE.getProduct();

    /**
     * The meta object literal for the '{@link org.xtext.example.idmproject.jsonParser.impl.ExpressionImpl <em>Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.idmproject.jsonParser.impl.ExpressionImpl
     * @see org.xtext.example.idmproject.jsonParser.impl.JsonParserPackageImpl#getExpression()
     * @generated
     */
    EClass EXPRESSION = eINSTANCE.getExpression();

    /**
     * The meta object literal for the '<em><b>Key</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXPRESSION__KEY = eINSTANCE.getExpression_Key();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSION__VALUE = eINSTANCE.getExpression_Value();

    /**
     * The meta object literal for the '{@link org.xtext.example.idmproject.jsonParser.impl.ValueImpl <em>Value</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.idmproject.jsonParser.impl.ValueImpl
     * @see org.xtext.example.idmproject.jsonParser.impl.JsonParserPackageImpl#getValue()
     * @generated
     */
    EClass VALUE = eINSTANCE.getValue();

    /**
     * The meta object literal for the '<em><b>String Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VALUE__STRING_VALUE = eINSTANCE.getValue_StringValue();

    /**
     * The meta object literal for the '<em><b>Integer Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VALUE__INTEGER_VALUE = eINSTANCE.getValue_IntegerValue();

    /**
     * The meta object literal for the '<em><b>Array</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VALUE__ARRAY = eINSTANCE.getValue_Array();

  }

} //JsonParserPackage
