/**
 * generated by Xtext 2.23.0
 */
package org.xtext.example.idmproject.jsonParser;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Json Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.idmproject.jsonParser.JsonModel#getBaseLoad <em>Base Load</em>}</li>
 *   <li>{@link org.xtext.example.idmproject.jsonParser.JsonModel#getInstructions <em>Instructions</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.idmproject.jsonParser.JsonParserPackage#getJsonModel()
 * @model
 * @generated
 */
public interface JsonModel extends EObject
{
  /**
   * Returns the value of the '<em><b>Base Load</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Base Load</em>' containment reference.
   * @see #setBaseLoad(Load)
   * @see org.xtext.example.idmproject.jsonParser.JsonParserPackage#getJsonModel_BaseLoad()
   * @model containment="true"
   * @generated
   */
  Load getBaseLoad();

  /**
   * Sets the value of the '{@link org.xtext.example.idmproject.jsonParser.JsonModel#getBaseLoad <em>Base Load</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Base Load</em>' containment reference.
   * @see #getBaseLoad()
   * @generated
   */
  void setBaseLoad(Load value);

  /**
   * Returns the value of the '<em><b>Instructions</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.idmproject.jsonParser.Instruction}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Instructions</em>' containment reference list.
   * @see org.xtext.example.idmproject.jsonParser.JsonParserPackage#getJsonModel_Instructions()
   * @model containment="true"
   * @generated
   */
  EList<Instruction> getInstructions();

} // JsonModel
