/**
 * generated by Xtext 2.23.0
 */
package org.xtext.example.idmproject.jsonParser;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Product</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.idmproject.jsonParser.JsonParserPackage#getProduct()
 * @model
 * @generated
 */
public interface Product extends Compute
{
} // Product
