/*
 * generated by Xtext 2.23.0
 */
package org.xtext.example.idmproject;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class JsonParserStandaloneSetup extends JsonParserStandaloneSetupGenerated {

	public static void doSetup() {
		new JsonParserStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
