/*
 * generated by Xtext 2.23.0
 */
package org.xtext.example.idmproject.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class JsonParserUiModule extends AbstractJsonParserUiModule {

	public JsonParserUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
