/*
 * generated by Xtext 2.23.0
 */
package org.xtext.example.idmproject.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.idmproject.JsonParserRuntimeModule;
import org.xtext.example.idmproject.JsonParserStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class JsonParserIdeSetup extends JsonParserStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new JsonParserRuntimeModule(), new JsonParserIdeModule()));
	}
	
}
