/*
 * generated by Xtext 2.23.0
 */
package org.xtext.example.idmproject.ide;


/**
 * Use this class to register ide components.
 */
public class JsonParserIdeModule extends AbstractJsonParserIdeModule {
}
