/**
 * generated by Xtext 2.23.0
 */
package org.xtext.example.idmproject.jsonParser.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.idmproject.jsonParser.Expression;
import org.xtext.example.idmproject.jsonParser.JsonParserPackage;
import org.xtext.example.idmproject.jsonParser.Modify;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Modify</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.idmproject.jsonParser.impl.ModifyImpl#getExpression <em>Expression</em>}</li>
 *   <li>{@link org.xtext.example.idmproject.jsonParser.impl.ModifyImpl#getNewExpression <em>New Expression</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ModifyImpl extends MinimalEObjectImpl.Container implements Modify
{
  /**
   * The cached value of the '{@link #getExpression() <em>Expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getExpression()
   * @generated
   * @ordered
   */
  protected Expression expression;

  /**
   * The cached value of the '{@link #getNewExpression() <em>New Expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNewExpression()
   * @generated
   * @ordered
   */
  protected Expression newExpression;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ModifyImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return JsonParserPackage.Literals.MODIFY;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Expression getExpression()
  {
    return expression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetExpression(Expression newExpression, NotificationChain msgs)
  {
    Expression oldExpression = expression;
    expression = newExpression;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, JsonParserPackage.MODIFY__EXPRESSION, oldExpression, newExpression);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setExpression(Expression newExpression)
  {
    if (newExpression != expression)
    {
      NotificationChain msgs = null;
      if (expression != null)
        msgs = ((InternalEObject)expression).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - JsonParserPackage.MODIFY__EXPRESSION, null, msgs);
      if (newExpression != null)
        msgs = ((InternalEObject)newExpression).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - JsonParserPackage.MODIFY__EXPRESSION, null, msgs);
      msgs = basicSetExpression(newExpression, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, JsonParserPackage.MODIFY__EXPRESSION, newExpression, newExpression));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Expression getNewExpression()
  {
    return newExpression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetNewExpression(Expression newNewExpression, NotificationChain msgs)
  {
    Expression oldNewExpression = newExpression;
    newExpression = newNewExpression;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, JsonParserPackage.MODIFY__NEW_EXPRESSION, oldNewExpression, newNewExpression);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setNewExpression(Expression newNewExpression)
  {
    if (newNewExpression != newExpression)
    {
      NotificationChain msgs = null;
      if (newExpression != null)
        msgs = ((InternalEObject)newExpression).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - JsonParserPackage.MODIFY__NEW_EXPRESSION, null, msgs);
      if (newNewExpression != null)
        msgs = ((InternalEObject)newNewExpression).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - JsonParserPackage.MODIFY__NEW_EXPRESSION, null, msgs);
      msgs = basicSetNewExpression(newNewExpression, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, JsonParserPackage.MODIFY__NEW_EXPRESSION, newNewExpression, newNewExpression));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case JsonParserPackage.MODIFY__EXPRESSION:
        return basicSetExpression(null, msgs);
      case JsonParserPackage.MODIFY__NEW_EXPRESSION:
        return basicSetNewExpression(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case JsonParserPackage.MODIFY__EXPRESSION:
        return getExpression();
      case JsonParserPackage.MODIFY__NEW_EXPRESSION:
        return getNewExpression();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case JsonParserPackage.MODIFY__EXPRESSION:
        setExpression((Expression)newValue);
        return;
      case JsonParserPackage.MODIFY__NEW_EXPRESSION:
        setNewExpression((Expression)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case JsonParserPackage.MODIFY__EXPRESSION:
        setExpression((Expression)null);
        return;
      case JsonParserPackage.MODIFY__NEW_EXPRESSION:
        setNewExpression((Expression)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case JsonParserPackage.MODIFY__EXPRESSION:
        return expression != null;
      case JsonParserPackage.MODIFY__NEW_EXPRESSION:
        return newExpression != null;
    }
    return super.eIsSet(featureID);
  }

} //ModifyImpl
